apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-submission-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grade-submission-api
  template:
    metadata:
      labels:
        app: grade-submission-api
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: grade-submission-api
        image: ghcr.io/sntushelo/kubernetes-cicd-tutorial:e154f99e8ca9f1893c8ac61c031fc3f9589d6af5
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: grade-submission-api
  namespace: default
spec:
  selector:
    app: grade-submission-api
  ports:
  - port: 3000
    targetPort: 30030
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: grade-submission-api-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: grade-submission-api
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30031
